services:
  enpm634_midterm_team22:
    image: r1zzg0d/enpm634-midterm-team22:latest
    container_name: enpm634_midterm_team22
    ports:
      - "5000:5000"
    volumes:
      - enpm634_midterm_team22_db:/app/data
      - enpm634_midterm_team22_uploads:/app/app/static/uploads

volumes:
  enpm634_midterm_team22_db:
  enpm634_midterm_team22_uploads:
